### ISSUE TITLE
WHMCS integration

### ISSUE THREAD

**Issue by uakfdotb** [LunaNode/lobster#26]
We could offer integration with WHMCS with a system where clients add credit via dummy WHMCS products that communicate with Lobster, registering credit and adding new user accounts if one matching WHMCS email address doesn't exist already. This will not happen if there's not enough interest. This may also not be the most effective integration model, so I'm open to suggestions.

**Comment by slrslr** [comment]
Hello, If there will be an WHMCS integration, what would be Lobster role in the process?
Example if i want to use OpenStack backend for VPS provisioning, Lobster role will be to receive commands from WHMCS and then communicate with OpenStack backend + return some result back to WHMCS? The client will not get in touch with Lobster, only with WHMCS?
Im certainly interested for such WHMCS integration.

**Comment by uakfdotb** [comment]
It's not clear what potential users would want, so that's why this issue is here, to determine the interest.

The idea formulated above would retain the Lobster panel for all functionality. The WHMCS integration would simply serve as a payment module and login redirection, so that:

a) when clients select the XYZ cloud service from WHMCS, they will be redirected to Lobster panel
b) clients can add seamlessly credit to Lobster via WHMCS one-time products

It is possible to have the functionality directly available in WHMCS module, but I think this doesn't make much sense with Lobster, since the commands might as well be forwarded directly to the VM backend. It may also be very cluttered to put everything in module, since there needs to be VM list, images, snapshots, volumes, create VM form, upload image form, etc. Perhaps you can clarify what you think would be better about having module instead of redirect to Lobster panel?

**Comment by uakfdotb** [comment]
Implemented what was described above:

* https://github.com/LunaNode/lobster/commit/d69a2bdc8932b1b6c17d90fa77fd470cba9895ab
* https://github.com/LunaNode/lobster-whmcs
