### ISSUE TITLE
install lobster

### ISSUE THREAD

**Issue by obaviet** [LunaNode/lobster#43]
Hey
i do not understand about install lobster
-system requirements

**Comment by uakfdotb** [comment]
Have you read through https://github.com/LunaNode/lobster/wiki/GettingStarted ? It is not clear to me what step you are stuck at. Lobster requires a MySQL database to be configured and a Linux system, libraries that it depends on are included in the binary and don't need to be installed separately.

**Comment by obaviet** [comment]
language go is difficult for me
I have not seen any public installation tutorial step by step
I hope to soon have the installation guide is easy to understand

**Comment by uakfdotb** [comment]
The getting started instructions do not require knowledge of Golang.
