### ISSUE TITLE
HTTPS Panel

### ISSUE THREAD

**Issue by rezabagh** [LunaNode/lobster#46]
hello, 

any idea how i could run the panel address in HTTPS on port 443 instead of simple HTTP ?
I mean Ex,

http://lobster.lunanode.com/ ---> https://lobster.lunanode.com/

Thank you

**Comment by uakfdotb** [comment]
Lobster is not intended to include full web server stack. The recommended setup with HTTPS is to use a reverse proxy from a web server. You can use the urlBase and proxyHeader settings.
