### ISSUE TITLE
about currency symbol

### ISSUE THREAD

**Issue by rezabagh** [LunaNode/lobster#49]
hello,

i have changed the currency to euro in lobster.cfg and now the paypal accept in euro , but i am wonder how i could change the currency symbol from $ to € in all part of client section (currency symbol, billing, ...)? Thank you for any advise.

; Currency that credit is based on.
; Payment gateways currently only accept payments in this currency.
currency = EUR

**Comment by uakfdotb** [comment]
Has been implemented in f3e14048788548d2af257f4d1ce4302e4fe31f82

You can modify currency_format in language/en_US.json
