### ISSUE TITLE
Another providers ?

### ISSUE THREAD

**Issue by amarc** [LunaNode/lobster#55]
Hello,

how open are you for adding another provider(s) other than currently listed ? For example, I would really love to have Leaseweb as they have virtual servers and bare metal per hour servers

http://developer.leaseweb.com/docs/

**Comment by uakfdotb** [comment]
Currently EC2, Google Compute, and better CloudStack are first on the todo list as far as VM interfaces go, but if you want to write one (either implementing Lobster VMI interface or Cloug computer provider interface) and submit a pull request then that'd be awesome.

**Comment by uakfdotb** [comment]
See #68
