### ISSUE TITLE
Digitalocean VM root password retrieve issue

### ISSUE THREAD

**Issue by rezabagh** [LunaNode/lobster#56]
hello, 

On Digital Ocean the cloud-init not working for a variety of OS to set the root password in lobster Panel.

Tahnks

**Comment by uakfdotb** [comment]
It looks like the user data is not working on some operating systems; for example, it does work on Ubuntu 14.04 and Debian 8.3 templates, but not on Debian 7.9. Also, the root password is not accessible except over e-mail (there's no API command to retrieve it or anything).

I thought this might only be failing for cloud-init scripts, but I tested with simple bash script and even that fails. So apparently DO user data support is basically broken for most of their templates...

The only option I see would be for users to provision a VM from the desired template, run install cloud-init (e.g. apt-get install cloud-init), and take a snapshot. I haven't tested to make sure this works but it should.

**Comment by uakfdotb** [comment]
Closing since there is no known way around this.
