### ISSUE TITLE
Correction in Bitcoin payment gateway 

### ISSUE THREAD

**Issue by rezabagh** [LunaNode/lobster#62]
hello, 

here in Bitcoin payment gateway the Description:      fmt.Sprintf("Credit $%.2f", amount) always get the currency in $ but it needs to be match to the real Billing.Currency, it would be nice to fix this. Thanks

https://github.com/LunaNode/lobster/blob/eba94cb8a6965e60a68417925af697246389d137/payment/coinbase/coinbase.go

				Name:             "Credit for " + username,
		PriceString:      fmt.Sprintf("%.2f", amount),
		PriceCurrencyIso: cfg.Billing.Currency,
		Custom:           fmt.Sprintf("lobster%d", userId),
		**Description:      fmt.Sprintf("Credit $%.2f", amount),**
		Type:             "buy_now",
		Style:            "buy_now_large",
		CallbackUrl:      cfg.Default.UrlBase + "/coinbase_callback_" + this.callbackSecret,

**Comment by uakfdotb** [comment]
Name will now use credit_for_username, and description will use currency_format
