### ISSUE TITLE
how to use wssh or novnc

### ISSUE THREAD

**Issue by jamesmr89** [LunaNode/lobster#64]
I'm trying to figure out how to use one of these protocols with a vultr server i have deployed.  I can't find anything doc wise about this.  how do i get this enabled, or is it even supported for vultr?

**Comment by uakfdotb** [comment]
The VM interface will automatically enable wssh or novnc proxy when needed, it only needs to be configured in lobster.cfg. Lobster handles both serving the frontend content for these console methods, and also handling the websocket connections.

Vultr now supports console (see 525182a24a1faf954211f0c519f0156ec8ff3b94), it will use the API server list to get KVM URL and simply redirect user to that URL.

**Comment by jamesmr89** [comment]
Is it possible to get a new binary pushed up to: https://github.com/LunaNode/lobster-release?

Thanks

**Comment by rezabagh** [comment]
Hello,
Thank you @uakfdotb for adding this great feature, that was the most needed feature, that would be great if you could push it to: https://github.com/LunaNode/lobster-release.

**Comment by uakfdotb** [comment]
The binary has been updated.
