### ISSUE TITLE
Expose Server Options for Vultr VMs

### ISSUE THREAD

**Issue by jamesmr89** [LunaNode/lobster#66]
These are currently hard coded. 

https://github.com/LunaNode/lobster/blob/master/vmi/vultr/vultr.go#L76

These should be exposed in the VM creation UI.

**Comment by uakfdotb** [comment]
Also similarly allow specifying auto backups, see #67

**Comment by jamesmr89** [comment]
This should also give the ability to select scripts (which I don't believe is currently available either, unless i'm missing something.

**Comment by uakfdotb** [comment]
Moving to #71, #72, and #73.
