### ISSUE TITLE
Ability to turn on Auto Backups on Vultr VM's

### ISSUE THREAD

**Issue by jamesmr89** [LunaNode/lobster#67]
This should be exposed in either the UI to the user, or in the the plan creation. 

from vultr api docs:

auto_backups string (optional) 'yes' or 'no'.  If yes, automatic backups will be enabled for this server (these have an extra charge associated with them)

If exposed to the user, it should change the price of the plan by a variable that can be set within the plan, ie "backup_price", and then when enabled it gets added to the plan price.  Or if not exposed to the end users, just add it as a checkbox in the plan setup so that admins can bake the price of the backups into the plan itself.

**Comment by uakfdotb** [comment]
Merging this issue with #66 since implementation would be similar.
