### ISSUE TITLE
paypal payment interface bug

### ISSUE THREAD

**Issue by rezabagh** [LunaNode/lobster#75]
Hello,

recently we faced to a credit card chargeback claim for one of our transaction which has been paid via paypal in the lobster panel, and unfortunately our transaction **was Not Eligible for Seller Protection** because the lobster does not provide paypal any shipping address (any address of the client ), please review this issue and **implement the client full postal address** in the lobster panel urgently, this is very critical that the payment via Paypal to be Eligible for Seller Protection to prevent any money loss as well as chargeback fees, this could be done by creating a client profile page in the lobster panel to update the client data with the mandatory postal address and optional phone/cell phone number field and the paypal payment interface use it in any transaction, also this is a good option to check and match the client email address and payer paypal email account which the payment has been done to protect us from any fraud orders.

**Comment by uakfdotb** [comment]
Implemented in 8c7910e233d794a219e93d8a32fafb24df22635b
